[package]
name = "search_pages"
version = "0.1.0"
authors = ["unvalley <kirohi.code@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = "1.0.126"
serde_derive = "1.0.126"
